# Generated by Django 5.1.2 on 2024-11-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
    ]
